name: Test Helm Deployment

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Ensure Namespace Exists
        run: |
          kubectl get namespace civic-dashboard || kubectl create namespace civic-dashboard
        shell: bash

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install civic-dashboard ./civic-dashboard \
            --namespace civic-dashboard \
            --create-namespace \
            --atomic \
            --cleanup-on-fail \
            --timeout 300s \
            --values ./civic-dashboard/values.yaml
        shell: bash

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/civic-dashboard-elasticsearch -n civic-dashboard
          kubectl rollout status deployment/civic-dashboard-postgres -n civic-dashboard
          kubectl rollout status deployment/civic-dashboard-data-fetcher -n civic-dashboard
        shell: bash

      - name: Probe Endpoints
        run: |
          kubectl run curl-pod --image=curlimages/curl:latest --rm -i --restart=Never -- \
            curl -f http://civic-dashboard-data-store:5000/healthz
          echo "All endpoints are healthy!"
        shell: bash
