name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [data-fetcher, data-store, sync-elastic]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Cache Docker layers
        uses: actions/cache@v4.2.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6.12.0
        with:
          context: services/${{ matrix.component }}
          push: true
          load: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.component }}:${{ github.event_name == 'push' && 'main' || github.head_ref }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test-helm:
    name: Test Helm Deployment
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Kind Cluster
        uses: helm/kind-action@v1.12.0
        with:
          version: v0.26.0
          
      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install civic-dashboard ./civic-dashboard \
            --namespace civic-dashboard \
            --create-namespace \
            --atomic \
            --cleanup-on-fail \
            --wait \
            --debug \
            --values ./civic-dashboard/values.yaml \
            --set-string images.dataFetcher.repository=ghcr.io/${{ github.repository_owner }}/data-fetcher \
            --set-string images.dataFetcher.tag=${{ github.sha }} \
            --set-string images.dataStore.repository=ghcr.io/${{ github.repository_owner }}/data-store \
            --set-string images.dataStore.tag=${{ github.sha }} \
            --set-string images.syncElastic.repository=ghcr.io/${{ github.repository_owner }}/sync-elastic \
            --set-string images.syncElastic.tag=${{ github.sha }}

      - name: Run Helm Tests
        run: |
          echo "Running Helm tests...";
          helm test civic-dashboard --namespace civic-dashboard
